---
name: "Jobs"
on: # yamllint disable
  workflow_call:
    inputs:
      # Default options for all jobs
      runs_on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-20.04"
        type: string

jobs:
  lint:
    runs-on: "${{ inputs.runs_on }}"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Install invoke"
        run: "pip install -U pip && pip install invoke"
      - name: "Linting"
        run: "invoke lint"
  unit:
    runs-on: "${{ inputs.runs_on }}"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          # - "3.10"
    env:
      INVOKE_NAUTOBOT_ANSIBLE_PYTHON_VER: "${{ matrix.python-version }}"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Install invoke"
        run: "pip install -U pip && pip install invoke"
      - name: "Tests"
        run: "invoke unit"
    needs:
      - "lint"
  integration:
    uses: ./.github/workflows/integration_tests.yml
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          # - "3.10"
        nautobot-version:
          - "1.4"
          - "1.5"
          - "1.6"
    needs:
      - "unit"
  publish_github:
    name: "Publish to GitHub"
    runs-on: "${{ inputs.runs_on }}"
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages"
        run: "pip install ansible-core"
      - name: "Build the collection"
        run: "ansible-galaxy collection build --output-path build"
      - name: "Upload binaries to release"
        uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.GH_NAUTOBOT_BOT_TOKEN }}"
          file: "build/*"
          tag: "${{ github.ref }}"
          overwrite: true
          file_glob: true
    needs:
      - "integration"
  publish_galaxy:
    name: "Publish to Ansible Galaxy"
    runs-on: "${{ inputs.runs_on }}"
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages"
        run: "pip install ansible-core"
      - name: "Build the collection"
        run: "ansible-galaxy collection build --output-path build"
      - name: "Publish the collection"
        run: "ansible-galaxy collection publish build/* --api-key=${{ secrets.GALAXY_API_TOKEN }}"
    needs:
      - "integration"
